modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = "https://github.com/Minenash/Seamless-Loading-Screen/issues"
license = "MIT"

[[mods]]
modId = "seamless_loading_screen"
version = "${version}"
displayName = "Seamless Loading Screen"
authors = "Minenash"
description = '''
Takes a screenshot of the game when you leave a world or server, and displays it when you rejoin it
'''
logoFile = "icon.png"
[[mixins]]
config = 'seamless_loading_screen-common.mixins.json'
[[mixins]]
config = 'seamless_loading_screen-neoforge.mixins.json'

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[mods."sodium:options"]
"mixin.features.gui.fast_loading_screen" = false
"features.gui.screen" = false

[[dependencies.seamless_loading_screen]]
modId = "neoforge"
required  = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless_loading_screen]]
modId = "yet_another_config_lib_v3"
required  = true
versionRange = "[3.5.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seamless_loading_screen]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"